version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${APP_IMAGE}
    container_name: ${APP_SERVICE_NAME}
    working_dir: ${APP_WORKDIR}
    volumes:
      - ./src:${APP_WORKDIR}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: php-fpm

  web:
    image: nginx:1.27-alpine
    container_name: ${WEB_SERVICE_NAME}
    depends_on:
      - app
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:${APP_WORKDIR}
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: ${DB_IMAGE}
    container_name: ${DB_SERVICE_NAME}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_SERVICE_NAME}
    ports:
      - "${REDIS_PORT}:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_SERVICE_NAME}
    ports:
      - "${MAILPIT_HTTP_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"

volumes:
  db_data:
